# Generated by Django 4.0.5 on 2022-06-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categoria_nombrecategoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_cliente')),
                ('nombre_cliente', models.CharField(max_length=50, verbose_name='nombre_cliente')),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id_categoria'),
        ),
    ]
