# Generated by Django 4.0.5 on 2022-06-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_alter_categoria_id_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo_cliente',
            field=models.CharField(max_length=200, null='no ingresado', verbose_name='correo_cliente'),
            preserve_default='no ingresado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_cliente',
            field=models.CharField(max_length=200, null='no ingresado', verbose_name='direccion_cliente'),
            preserve_default='no ingresado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_cliente',
            field=models.CharField(max_length=200, null='no ingresado', verbose_name='telefono_cliente'),
            preserve_default='no ingresado',
        ),
    ]
