# Generated by Django 4.0.5 on 2022-06-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cliente_telefono_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono_cliente',
            field=models.IntegerField(null='no ingresado', verbose_name='telefono_cliente'),
        ),
    ]
